const CONFIG = {
  DB_SPREADSHEET_ID: '194C4nXsWYCEQEsuwuWVmZ18XJrGs8B_gGmhg698wfsY',
  SOURCE_SPREADSHEET_ID: '1Wan-sIlRIgqO98wVnNj0L_KBRpwwakGFSpYr_w5OFqk',
  SLACK_DEFAULT_CHANNEL: 'C0BGD8Q6GUW',
  SLACK_WEBHOOK_URL_PROPERTY: 'FINANCE_WORKFLOW_SLACK_WEBHOOK_URL',
};
